#spring:
#  datasource:
#        username: root
#        password: root
#        url: jdbc:mysql://localhost:3306/employee
#        driver-class-name: com.mysql.cj.jdbc.Driver
#     jpa:
#        spring.jpa.show-sql = true
#        spring.jpa.hibernate.ddl-auto =update
#        spring.jpa.properties.hibernate.dialect =org.hibernate.dialect.MySQL5Dialect